plugins:
  - serverless-offline
  - serverless-plugin-typescript-express

service: pintap-test-ts
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/server.handler
    events: 
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  serverless-offline:
    noPrependStageInUrl: true
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
